name: SellUI
main: SellUI\DaDevGuy\Main
author: DaDevGuy
version: 1.0.0
api: [4.0.0]
depend:
  - SellAll
commands:
  sellui:
    description: "Open SellUI"
    permission: sellui.use
permissions:
  sellui.use:
    default: true
